#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[181] =
    {   0,
        0,    0,    0,    0,   55,   51,   50,   54,   51,    2,
       51,   51,   51,   42,   42,   42,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       51,   53,   52,    0,   44,   42,    0,    0,    0,    0,
        0,   40,   39,    0,    0,    0,   48,   49,    0,    0,
        0,   46,   46,   19,   46,   46,   46,   46,   46,   20,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   21,    0,    0,    0,    0,   36,   18,    0,    0,
        0,    0,    0,    0,   48,   48,    0,    0,    0,   49,
       49,   37,   38,   46,   46,   46,   46,   46,   46,   46,

       46,   24,   46,   46,   46,   46,   46,   46,    9,   46,
       46,   46,   46,   46,   41,   17,    0,   13,    0,    0,
        0,    0,    0,   47,   46,   25,    8,   22,   46,   23,
       46,   46,   46,   46,   46,   26,   46,   46,   46,   46,
       46,   46,   46,   46,    0,   45,    0,   14,   12,   10,
       15,   11,    0,   47,   47,   33,    5,   46,   27,   46,
       46,   46,   29,   31,    6,   35,   46,   30,   32,   46,
        0,   46,   28,    3,   34,    4,    7,   16,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,    9,   10,
       11,    9,    9,    9,    9,    9,    9,   12,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   33,   34,   35,   36,   37,
        1,    1,    1,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   22,   48,   49,   50,   51,
       52,   53,   22,   54,   55,   56,   57,   58,   59,   60,
       61,   62,    1,    1,    1,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    2,    2,
        2,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    2,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1
    } ;

static const flex_int16_t yy_base[191] =
    {   0,
        0,    0,  152,  136,  134, 1042, 1042, 1042,  121, 1042,
       55,    0,    0,   68,   80,  104,   94,  110,  120,  126,
      132,  187,  150,  159,  239,  140,  174,  226,  198,  212,
      111, 1042, 1042,   84, 1042,  153,   51,   52,   97,   54,
       62,   94, 1042,  124,   56,  131,  232,  261,  147,  151,
      178,  248,  254,  271,  279,  286,  292,  301,  311,  317,
      327,  333,  351,  339,  384,  363,  373,  379,  436,  404,
      427,  448,   19,  174,  171,  196, 1042, 1042,  236,  243,
      238,  255,  192,  304,  460,  466,  354,    0,    0,  476,
      488, 1042, 1042,  494,  500,  509,  516,  522,  529,  545,

      552,  558,  574,  581,  587,  597,  603,  609,  624,  634,
      640,  647,  656,  662, 1042, 1042,  230, 1042,  276,  320,
      335,  338,  274,  669,  676,  687,  694,  700,  706,  713,
      721,  727,  734,  740,  749,  765,  771,  777,  783,  791,
      806,  812,  819,  832,  408,  840,  303, 1042, 1042, 1042,
     1042, 1042,  439,  846,  853,  860,  866,  875,  881,  887,
      893,  902,  911,  917,  923,  929,  938,  944,  953,  959,
      358,  965,  971,  982,  988,  994, 1000, 1042, 1007, 1042,
     1018, 1022,   76,   70, 1025, 1028, 1031, 1034,   68, 1037
    } ;

static const flex_int16_t yy_def[191] =
    {   0,
      180,    1,  181,  181,  180,  180,  180,  180,  182,  180,
      180,  183,  184,  180,  180,  180,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      180,  180,  180,  182,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  186,  187,  180,  180,
      180,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,   22,  185,  185,  185,  185,  185,
      188,  185,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  186,  186,  180,  189,  184,  187,
      187,  180,  180,  185,  185,  185,  185,  185,  185,  185,

      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  190,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  180,  185,  180,  180,  180,  180,
      180,  180,  180,  190,  190,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      180,  185,  185,  185,  185,  185,  185,  180,  185,    0,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180
    } ;

static const flex_int16_t yy_nxt[1106] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,    6,   17,   18,   19,   20,   21,   22,   17,   17,
       23,   17,   17,   24,   25,   17,   17,   26,   27,   17,
       17,   28,   29,   30,   17,   17,   17,    6,   17,   18,
       19,   20,   21,   22,   17,   17,   23,   17,   24,   25,
       17,   17,   26,   27,   17,   17,   28,   29,   30,   17,
       17,   17,   31,   36,   36,   36,   74,   37,   75,   78,
       38,  124,   39,   48,   79,   40,   36,   36,   36,   47,
       41,  115,   42,   43,   44,   45,   46,   35,   36,   36,
       36,   82,   74,   37,   75,   78,   38,   49,   39,   51,

       79,   40,   52,   52,   52,   41,   80,   42,   43,   44,
       45,   46,   36,   36,   36,   51,   82,   76,   52,   52,
       52,   50,   73,   49,   35,   51,   77,   54,   52,   52,
       52,   51,   80,  180,   52,   52,   52,   51,   33,   55,
       52,   52,   52,   76,   81,   51,   56,   50,   52,   52,
       52,   77,   67,   54,   33,   51,   83,  180,   52,   52,
       52,   36,   36,   36,   51,   55,   57,   52,   52,   52,
       81,  180,   56,  180,  180,   62,   92,  180,   67,   51,
       93,   83,   52,   52,   52,   63,   52,   52,   52,  116,
       68,   57,   51,  180,  117,   52,   52,   52,   69,   58,

       62,   92,   59,   51,   60,   93,   52,   52,   52,  180,
       63,  180,  123,   71,  180,  116,   68,   51,   61,  117,
       52,   52,   52,   69,  180,   58,  118,  180,   59,   72,
       60,   51,  180,  180,   52,   52,   52,   84,  123,   71,
       85,   85,   85,   61,   51,  180,  147,   52,   52,   52,
       70,  118,   64,   51,  180,   72,   52,   52,   52,   51,
      119,   65,   52,   52,   52,   66,   87,   88,   89,   90,
       90,   90,  147,  120,  121,   70,   51,  180,   64,   52,
       52,   52,  122,  180,   51,  119,   65,   52,   52,   52,
       66,   51,  148,  180,   52,   52,   52,   51,  120,  121,

       52,   52,   52,   94,  152,  180,   51,  122,   96,   52,
       52,   52,   85,   85,   85,   95,   51,  180,  148,   52,
       52,   52,   51,  180,  180,   52,   52,   52,   94,  152,
       97,   98,   51,  171,   96,   52,   52,   52,   51,  149,
       95,   52,   52,   52,   51,  180,  180,   52,   52,   52,
       99,  150,  180,  100,  151,   97,   51,   98,  171,   52,
       52,   52,   90,   90,   90,  149,  180,  102,   51,  101,
      180,   52,   52,   52,  178,   99,  180,  150,   51,  100,
      151,   52,   52,   52,   51,  180,  180,   52,   52,   52,
      180,  180,  102,  180,  107,  101,   53,  180,  180,  103,

      178,  104,  105,  180,  108,  180,  109,  180,  180,   51,
      180,  180,   52,   52,   52,  106,  146,  146,  146,  107,
      180,  180,   53,  180,  180,  103,  180,  104,  105,  108,
      113,  109,   51,  180,  180,   52,   52,   52,  180,  180,
      106,   51,  180,  180,   52,   52,   52,  154,  154,  154,
      180,  110,  180,   51,  111,  113,   52,   52,   52,  180,
      180,  180,  180,  180,   53,   84,  180,  112,   85,   85,
       85,   84,  180,  180,   85,   85,   85,  110,  180,  180,
      111,   87,   88,   89,   90,   90,   90,  180,  180,  180,
      180,  180,  112,   87,   88,   89,   90,   90,   90,   51,

      180,  180,   52,   52,   52,   51,  180,  180,   52,   52,
       52,  180,  180,  180,   51,  180,  180,   52,   52,   52,
      125,   51,  126,  127,   52,   52,   52,   51,  180,  180,
       52,   52,   52,  180,   51,  180,  180,   52,   52,   52,
      180,  180,  180,  180,  180,  125,  128,  126,  180,  127,
       51,  129,  130,   52,   52,   52,  180,   51,  180,  180,
       52,   52,   52,   51,  180,  180,   52,   52,   52,  180,
      180,  128,  132,  180,  180,  131,  129,  130,  133,   51,
      180,  180,   52,   52,   52,  180,   51,  180,  180,   52,
       52,   52,   51,  180,  134,   52,   52,   52,  132,  180,

      131,  135,   51,  133,  180,   52,   52,   52,   51,  180,
      136,   52,   52,   52,   51,  137,  180,   52,   52,   52,
      134,  180,  180,  180,  180,  180,  138,  135,  139,   51,
      180,  180,   52,   52,   52,  136,  180,  180,  140,   51,
      137,  180,   52,   52,   52,   51,  180,  180,   52,   52,
       52,  138,   51,  139,  141,   52,   52,   52,  180,  180,
      180,   51,  180,  140,   52,   52,   52,  145,  142,  180,
      146,  146,  146,  180,  153,  180,  143,  154,  154,  154,
      141,   51,  180,  180,   52,   52,   52,  144,  180,  180,
      180,  156,   51,  142,  180,   52,   52,   52,  180,   51,

      180,  143,   52,   52,   52,   51,  180,  180,   52,   52,
       52,   51,  144,  180,   52,   52,   52,  156,   51,  180,
      180,   52,   52,   52,  180,  180,   51,  180,  157,   52,
       52,   52,   51,  180,  180,   52,   52,   52,  180,   51,
      180,  158,   52,   52,   52,   51,  180,  180,   52,   52,
       52,  180,  159,  157,   51,  180,  180,   52,   52,   52,
      180,  180,  180,  180,  180,  160,  180,  158,  180,  161,
       51,  180,  162,   52,   52,   52,   51,  159,  180,   52,
       52,   52,   51,  180,  180,   52,   52,   52,   51,  180,
      160,   52,   52,   52,  161,  180,   51,  162,  163,   52,

       52,   52,  180,  180,  180,  164,  180,  166,  180,  180,
      180,   51,  180,  165,   52,   52,   52,   51,  180,  180,
       52,   52,   52,  163,   51,  180,  180,   52,   52,   52,
      164,  180,  180,  166,  180,  167,  180,   51,  165,  168,
       52,   52,   52,  180,  180,   51,  180,  169,  146,  146,
      146,  153,  180,  180,  154,  154,  154,  170,  153,  180,
      167,  154,  154,  154,  168,   51,  180,  180,   52,   52,
       52,   51,  169,  180,   52,   52,   52,  180,  180,  180,
       51,  180,  170,   52,   52,   52,   51,  172,  180,   52,
       52,   52,   51,  180,  180,   52,   52,   52,   51,  180,

      180,   52,   52,   52,  180,  180,  180,   51,  180,  180,
       52,   52,   52,  172,  180,  174,   51,  173,  175,   52,
       52,   52,   51,  180,  180,   52,   52,   52,   51,  180,
      180,   52,   52,   52,   51,  180,  180,   52,   52,   52,
      174,  180,  173,   51,  175,  180,   52,   52,   52,   51,
      180,  180,   52,   52,   52,  180,  180,  180,   51,  180,
      176,   52,   52,   52,   51,  180,  180,   52,   52,   52,
       51,  180,  180,   52,   52,   52,   51,  180,  180,   52,
       52,   52,  180,  180,  180,  176,  180,   51,  179,  177,
       52,   52,   52,   51,  180,  180,   52,   52,   52,   51,

      180,  180,   52,   52,   52,   51,  180,  180,   52,   52,
       52,  180,   51,  179,  177,   52,   52,   52,   32,   32,
       32,   32,   34,   34,   34,   34,   53,  180,   53,   86,
      180,   86,   91,   91,   91,  114,  180,  114,  155,  180,
      155,    5,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  180,  180,  180
    } ;

static const flex_int16_t yy_chk[1106] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   11,   11,   37,   11,   38,   40,
       11,  189,   11,  184,   41,   11,   14,   14,   14,  183,
       11,   73,   11,   11,   11,   11,   11,   34,   15,   15,
       15,   45,   37,   11,   38,   40,   11,   15,   11,   17,

       41,   11,   17,   17,   17,   11,   42,   11,   11,   11,
       11,   11,   16,   16,   16,   18,   45,   39,   18,   18,
       18,   16,   31,   15,    9,   19,   39,   18,   19,   19,
       19,   20,   42,    5,   20,   20,   20,   21,    4,   19,
       21,   21,   21,   39,   44,   26,   20,   16,   26,   26,
       26,   39,   26,   18,    3,   23,   46,    0,   23,   23,
       23,   36,   36,   36,   24,   19,   21,   24,   24,   24,
       44,    0,   20,    0,    0,   23,   49,    0,   26,   27,
       50,   46,   27,   27,   27,   24,   51,   51,   51,   74,
       27,   21,   22,    0,   75,   22,   22,   22,   27,   22,

       23,   49,   22,   29,   22,   50,   29,   29,   29,    0,
       24,    0,   83,   29,    0,   74,   27,   30,   22,   75,
       30,   30,   30,   27,    0,   22,   76,    0,   22,   30,
       22,   28,    0,    0,   28,   28,   28,   47,   83,   29,
       47,   47,   47,   22,   25,    0,  117,   25,   25,   25,
       28,   76,   25,   52,    0,   30,   52,   52,   52,   53,
       79,   25,   53,   53,   53,   25,   48,   48,   48,   48,
       48,   48,  117,   80,   81,   28,   54,    0,   25,   54,
       54,   54,   82,    0,   55,   79,   25,   55,   55,   55,
       25,   56,  119,    0,   56,   56,   56,   57,   80,   81,

       57,   57,   57,   55,  123,    0,   58,   82,   57,   58,
       58,   58,   84,   84,   84,   56,   59,    0,  119,   59,
       59,   59,   60,    0,    0,   60,   60,   60,   55,  123,
       58,   59,   61,  147,   57,   61,   61,   61,   62,  120,
       56,   62,   62,   62,   64,    0,    0,   64,   64,   64,
       61,  121,    0,   62,  122,   58,   63,   59,  147,   63,
       63,   63,   87,   87,   87,  120,    0,   64,   66,   63,
        0,   66,   66,   66,  171,   61,    0,  121,   67,   62,
      122,   67,   67,   67,   68,    0,    0,   68,   68,   68,
        0,    0,   64,    0,   66,   63,   65,    0,    0,   65,

      171,   65,   65,    0,   67,    0,   68,    0,    0,   70,
        0,    0,   70,   70,   70,   65,  145,  145,  145,   66,
        0,    0,   65,    0,    0,   65,    0,   65,   65,   67,
       70,   68,   71,    0,    0,   71,   71,   71,    0,    0,
       65,   69,    0,    0,   69,   69,   69,  153,  153,  153,
        0,   69,    0,   72,   69,   70,   72,   72,   72,    0,
        0,    0,    0,    0,   71,   85,    0,   69,   85,   85,
       85,   86,    0,    0,   86,   86,   86,   69,    0,    0,
       69,   90,   90,   90,   90,   90,   90,    0,    0,    0,
        0,    0,   69,   91,   91,   91,   91,   91,   91,   94,

        0,    0,   94,   94,   94,   95,    0,    0,   95,   95,
       95,    0,    0,    0,   96,    0,    0,   96,   96,   96,
       94,   97,   95,   96,   97,   97,   97,   98,    0,    0,
       98,   98,   98,    0,   99,    0,    0,   99,   99,   99,
        0,    0,    0,    0,    0,   94,   97,   95,    0,   96,
      100,   98,   99,  100,  100,  100,    0,  101,    0,    0,
      101,  101,  101,  102,    0,    0,  102,  102,  102,    0,
        0,   97,  101,    0,    0,  100,   98,   99,  101,  103,
        0,    0,  103,  103,  103,    0,  104,    0,    0,  104,
      104,  104,  105,    0,  103,  105,  105,  105,  101,    0,

      100,  104,  106,  101,    0,  106,  106,  106,  107,    0,
      104,  107,  107,  107,  108,  105,    0,  108,  108,  108,
      103,    0,    0,    0,    0,    0,  106,  104,  107,  109,
        0,    0,  109,  109,  109,  104,    0,    0,  108,  110,
      105,    0,  110,  110,  110,  111,    0,    0,  111,  111,
      111,  106,  112,  107,  110,  112,  112,  112,    0,    0,
        0,  113,    0,  108,  113,  113,  113,  114,  111,    0,
      114,  114,  114,    0,  124,    0,  112,  124,  124,  124,
      110,  125,    0,    0,  125,  125,  125,  113,    0,    0,
        0,  125,  126,  111,    0,  126,  126,  126,    0,  127,

        0,  112,  127,  127,  127,  128,    0,    0,  128,  128,
      128,  129,  113,    0,  129,  129,  129,  125,  130,    0,
        0,  130,  130,  130,    0,    0,  131,    0,  129,  131,
      131,  131,  132,    0,    0,  132,  132,  132,    0,  133,
        0,  131,  133,  133,  133,  134,    0,    0,  134,  134,
      134,    0,  132,  129,  135,    0,    0,  135,  135,  135,
        0,    0,    0,    0,    0,  133,    0,  131,    0,  134,
      136,    0,  135,  136,  136,  136,  137,  132,    0,  137,
      137,  137,  138,    0,    0,  138,  138,  138,  139,    0,
      133,  139,  139,  139,  134,    0,  140,  135,  137,  140,

      140,  140,    0,    0,    0,  138,    0,  140,    0,    0,
        0,  141,    0,  139,  141,  141,  141,  142,    0,    0,
      142,  142,  142,  137,  143,    0,    0,  143,  143,  143,
      138,    0,    0,  140,    0,  141,    0,  144,  139,  142,
      144,  144,  144,    0,    0,  146,    0,  143,  146,  146,
      146,  154,    0,    0,  154,  154,  154,  144,  155,    0,
      141,  155,  155,  155,  142,  156,    0,    0,  156,  156,
      156,  157,  143,    0,  157,  157,  157,    0,    0,    0,
      158,    0,  144,  158,  158,  158,  159,  158,    0,  159,
      159,  159,  160,    0,    0,  160,  160,  160,  161,    0,

        0,  161,  161,  161,    0,    0,    0,  162,    0,    0,
      162,  162,  162,  158,    0,  161,  163,  160,  162,  163,
      163,  163,  164,    0,    0,  164,  164,  164,  165,    0,
        0,  165,  165,  165,  166,    0,    0,  166,  166,  166,
      161,    0,  160,  167,  162,    0,  167,  167,  167,  168,
        0,    0,  168,  168,  168,    0,    0,    0,  169,    0,
      167,  169,  169,  169,  170,    0,    0,  170,  170,  170,
      172,    0,    0,  172,  172,  172,  173,    0,    0,  173,
      173,  173,    0,    0,    0,  167,    0,  174,  172,  170,
      174,  174,  174,  175,    0,    0,  175,  175,  175,  176,

        0,    0,  176,  176,  176,  177,    0,    0,  177,  177,
      177,    0,  179,  172,  170,  179,  179,  179,  181,  181,
      181,  181,  182,  182,  182,  182,  185,    0,  185,  186,
        0,  186,  187,  187,  187,  188,    0,  188,  190,    0,
      190,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  180,  180,  180
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 2 "lexico.l"
    #include <iostream>
    #include "parser.h"
    #include <QList>
    char coment[400];
    int yylex();
    void yyerror(const char *s);
    int linea = 0;
    int columna = 1;
    int anterior = 0;
    QList<Node> *listNodos;
#line 760 "scanner.cpp"

#line 762 "scanner.cpp"

#define INITIAL 0
#define COM 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "lexico.l"

#line 982 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 181 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1042 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "lexico.l"

	YY_BREAK

case 2:
YY_RULE_SETUP
#line 35 "lexico.l"
{ BEGIN COM; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "lexico.l"
{ return mkdisk; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "lexico.l"
{ return rmdisk; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexico.l"
{ return fdisk; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "lexico.l"
{ return mount; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "lexico.l"
{ return umount; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "lexico.l"
{ return exec; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "lexico.l"
{ return rep; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexico.l"
{ return size; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexico.l"
{ return unit; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexico.l"
{ return path; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexico.l"
{ return fit; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexico.l"
{ return name; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexico.l"
{ return type; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexico.l"
{ return del; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexico.l"
{ return add; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexico.l"
{ return id; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexico.l"
{ return bf; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexico.l"
{ return ff; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexico.l"
{ return wf; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexico.l"
{ return fast; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexico.l"
{ return full; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexico.l"
{ return mbr; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexico.l"
{ return disk; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "lexico.l"
{ return mkfs; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "lexico.l"
{ return login; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "lexico.l"
{ return logout; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "lexico.l"
{ return mkgrp; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "lexico.l"
{ return rmgrp; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "lexico.l"
{ return mkusr; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "lexico.l"
{ return rmusr; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "lexico.l"
{ return Rchmod; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "lexico.l"
{ return mkfile; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "lexico.l"
{ return pausa; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "lexico.l"
{ return fs; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "lexico.l"
{ return fs2; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "lexico.l"
{ return fs3; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "lexico.l"
{ return r; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "lexico.l"
{ return p; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "lexico.l"
{ return igual; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "lexico.l"
{strcpy(yylval.text, yytext); return num;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "lexico.l"
{strcpy(yylval.text, yytext); return caracter;}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 83 "lexico.l"
{strcpy(yylval.text, yytext); return cadena;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "lexico.l"
{strcpy(yylval.text, yytext); return idmount;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "lexico.l"
{strcpy(yylval.text, yytext); return identificador;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "lexico.l"
{strcpy(yylval.text, yytext); return ruta;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "lexico.l"
{strcpy(yylval.text, yytext); return extension;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "lexico.l"
{strcpy(yylval.text, yytext); return directorio;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "lexico.l"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "lexico.l"
{std::cout <<yytext <<" Error Lexico" << std::endl;}
	YY_BREAK

case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 95 "lexico.l"
{ BEGIN INITIAL; /*strcpy(yylval.text, coment); memset(coment,0,400); return comentario;*/ };
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "lexico.l"
{ /*strcat(coment, yytext);*/ };
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 98 "lexico.l"
ECHO;
	YY_BREAK
#line 1313 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 181 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 181 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 180);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 98 "lexico.l"


